# Generated by Django 5.0.6 on 2024-05-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cab",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cab_identifier", models.CharField(max_length=20, unique=True)),
                ("cab_model", models.CharField(max_length=100)),
                ("is_available", models.BooleanField(default=True)),
                ("latitude", models.IntegerField()),
                ("longitude", models.IntegerField()),
            ],
            options={
                "db_table": "cabs",
            },
        ),
        migrations.CreateModel(
            name="Passenger",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "db_table": "passengers",
                "indexes": [
                    models.Index(fields=["email"], name="passengers_email_620f4f_idx"),
                    models.Index(
                        fields=["created_at"], name="passengers_created_d33061_idx"
                    ),
                ],
            },
        ),
    ]
